config/routes.rb
Rails.application.routes.draw do
  Healthcheck.routes(self)
  devise_for :users
  resources :friends
  #get 'home/index'
  get 'home/about'
  #root 'home#index'
  root 'friends#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password, :password_confirmation, :current_password])
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
     @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to root_path, status: :see_other, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

   def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized To Edit This Friend....Buddy! Try editing your own friends Chief!" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :character_most_like, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    @about_me = "My Name is Travis Stephenson..."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend, local: true) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">

    <% form.label :first_name %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>
</br>
  <div class="field form-group">
    <% form.label :last_name %>
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name"  %>
  </div>
</br>
  <div class="field form-group">
    <% form.label :email %>
    <%= form.text_field :email, class:"form-control", placeholder:"email"  %>
  </div>
</br>
  <div class="field form-group">
    <% form.label :phone %>
    <%= form.text_field :phone, class:"form-control", placeholder:"phone"  %>
  </div>
</br>
  <div class="field form-group">
    <% form.label :character_most_like %>
    <%= form.text_field :character_most_like, class:"form-control", placeholder:"Character You are Most Like"  %>
  </div>

</br>

<div class="field form-group">
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value: current_user.id, type: :hidden   %>
  </div>

 
  <div class="actions">
    <%= form.submit class: 'btn btn-info'%>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Character most like:</strong>
    <%= friend.character_most_like %>
  </p>

</div>

app/views/friends/edit.html.erb
<div class="card bg-light mb-3">
  <div class="card-header"><h1>Editing friend</h1></div>
  <div class="card-body">
    <%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend, class:"btn btn-secondary" %> |
   <%= link_to "Delete", @friend, method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this friend?' }, class: 'btn btn-danger' %>  |
    <%= link_to "Back to friends", friends_path, class:"btn btn-secondary" %>  
 
  
</div>

  </div>
</div>

app/views/friends/index.html.erb
 <% if user_signed_in? %>
 <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Character Most Like:</th>
       <th></th>
    </tr>
  </thead>

   <tbody>
      <% @friends.each do |friend| %>
        <% if friend.user == current_user %>
        <tr>
          <td>
<%= link_to friend.first_name + ' ' + friend.last_name, friend %>


          </td>
          
          <td><%= friend.email %></td>
          <td><%= friend.phone %></td>
          <td><%= friend.character_most_like %></td>
          
          
         
          
          
          
           <td><%= link_to 'Delete', 
          friend_path(friend), data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this friend?' }, class: 'btn btn-outline-danger' %>
          
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Add Friend', new_friend_path, class:"btn btn-secondary" %>

<% else %>


<div class="card bg-light mb-3">
  <div class="row no-gutters">
    <div class="col-md-4">
      <img src="https://i.ibb.co/d5rYgzD/292c0c26-2da3-4bcf-9491-ab1d7ac32fe4.gif"   border="0" class="card-img, img-fluid, img-thumbnail" alt="Responsive image">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        
        <h1 class="card-title" style="font-family: 'Luckiest Guy', cursive;"> <span class="text-primary">Welcome</span> <span class="text-success"> To </span> <span class="text-danger"> Ciri </span> <span class="text-warning"> and </span> <span style="color:purple">Friends </span> <span style="color:darkturquoise;"> App </span></h1>
        
        <div class="btn-group btn-group-lg" role="group" aria-label="Buttons"> <h1><%= link_to "Sign Up",new_user_registration_path, class:"btn btn-info btn-lg mr-3" %></h1>   <br/><br/>
         
         <h1><%= link_to "Sign In", new_user_session_path, class:"btn btn-primary btn-lg" %></h1></div>
        
       

      </div>
    </div>
  </div>
</div>


<style>
@import url('https://fonts.googleapis.com/css2?family=Luckiest+Guy&display=swap');
</style>

<% end %>

app/views/friends/new.html.erb
<div class="card bg-light mb-3">
  <div class="card-header">
    <h1>Add Friend</h1>
</div>
 
  <div class="card-body">
   </br>
<%= render "form", friend: @friend %>

</br>

<div>
  <%= link_to "Back to friends", friends_path, class:"btn btn-secondary" %>
</div>
  </div>
</div>

app/views/friends/show.html.erb
<div class="card bg-light mb-3">
  <div class="card-header">
    <h1 class="display-4">
    <%= @friend.first_name %>
    <%= @friend.last_name %>
  </h1>
</div>

  <div class="card-body">
    <p class="lead">
    <%= @friend.email %>  | 
    <%= @friend.phone %>  |  
    <%= @friend.character_most_like %>

  </p>
  <br/>

  <%= link_to "Edit", @friend, class:"btn btn-info" %> |
   <%= link_to "Delete", @friend, data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this friend?' }, class: 'btn btn-danger' %> |

  <%= link_to "Back", friends_path, class:"btn btn-secondary" %> 
<br/><br/>

  

  </div>
</div>


   
 





  

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
 <a class="navbar-brand" href="#">
    <img src="https://i.ibb.co/wBGtTvz/ciri.png" alt="ciri" width="125" height="125" class="d-inline-block align-top" alt="">
     <%= link_to 'Ciri and Friends App',
      root_path, class:"navbar-brand" %>
  </a>


  
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    
       
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
    
        <li class="nav-item">
          <%= link_to "About Us", 
              home_about_path, class:"nav-link" %>


      
      <% if user_signed_in? %>

        <li class="nav-item">
          <%= link_to "Add a Friend", 
            new_friend_path, class:"nav-link" %>
        </li>

       <li class="nav-item">
        <%= link_to "Sign Out", 
            destroy_user_session_path, method: :delete, class:"nav-link" %>
       </li>

       <li class="nav-item">
        <%= link_to "Edit Profile", 
            edit_user_registration_path, class:"nav-link" %>
       </li>

      

      <% else %>

        <li class="nav-item">
          <%= link_to "Sign Up", 
              new_user_registration_path, class:"nav-link" %>
        </li> 

        <li class="nav-item">
          <%= link_to "Sign In", 
              new_user_session_path, class:"nav-link" %>
        </li> 
      <% end %>   
     
     
    </ul>
    
     <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us...</h1>

<p>
	<%= @about_me %>
</p>

app/views/home/index.html.erb
<h1>Hello World!</h1>
This is my first Rails Page...

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>Ciri and Friends App</title>
     

     <%= csrf_meta_tags %>
     <%= csp_meta_tag %>

     <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
     <%= javascript_importmap_tags %>
  </head>
  <body>

    <%= render 'home/header' %>
    <div class="container">
      <br/>


      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>

      
      
    <%= yield %>

    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
   <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>